### PR TITLE
Refactor format handlers into dedicated subclasses; add new one

### PR DESCRIPTION
**Pull request by geomat0101**

### CODE REVIEW

**Comment by jmcameron** [comment]
Hi @geomat0101 !  Thanks for the update.  Could you explain what motivated you to make these changes?  Also I'd like for you to update the main README.md file with your updates?

Thanks
-Jonathan

**Comment by jmcameron** [comment]
@geomat0101 Also, could you email me a couple of files to test this new version on?  I'd like to try your new additions.   My email is at the bottom of the main README.md file.  Thanks

**Comment by geomat0101** [comment]
Howdy Jonathan!

I've recently been resurrecting an old personal finance platform I built back before AMEX discontinued QIF support ([geomat0101/acct](https://github.com/geomat0101/acct)) and stumbled upon this project somehow looking to convert their csv format into something I could easily consume there.

None of the existing format options matched what I was working with, but the bones are there and are good, so I opted to extend this to support yet another csv format version.

In doing so, I saw that the format-specific row handlers were implemented via an if..elif..else block that was beginning to grow cumbersome with the number of supported format versions, so I decided to abstract all that out into a separate row iterator with individual subclasses for each of the format version implementations.  This makes it super easy to extend going forward, reduces the cyclomatic complexity of the original implementation substantially, and makes developing unit tests for it all much easier (should someone be inspired enough to do so at some point :wink: )

Will send a sample csv that adheres to the new format i added (--format 4).  It parses clean using [my QIF implementation](https://github.com/geomat0101/acct/blob/main/pylib/acct/qif.py).

Thanks for reviewing
-Matt

**Review by jmcameron — APPROVED** [review]
Matt, thanks  for this update.   I did test it with the .csv file you provided and it works fine.
And thanks for updating the readme file.

**Pull request merged**
